spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 1
      timeout: 2000ms # 超时时间
      lettuce:
        pool:
          max-active: 100 # 最大连接数
          max-idle: 10 # 最大空闲连接数
          min-idle: 5 # 最小空闲连接数
          max-wait: 5000ms # 最大等待时间

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itheima.pojo
  configuration:
    map-underscore-to-camel-case: true

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: big-event-showing
    region: cn-beijing

# PageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  auto-runtime-dialect: true